# Generated by Django 3.1.6 on 2021-04-14 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bannercarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Top Banner Carousel (Slideshow)',
            },
        ),
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/Banner_Images')),
                ('link', models.CharField(blank=True, max_length=350, null=True)),
                ('bannercarousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.bannercarousel')),
            ],
        ),
    ]
