# Generated by Django 3.1.6 on 2021-04-15 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubCategories', '0001_initial'),
        ('Brand', '0001_initial'),
        ('Shop', '0014_product_int_average_rating'),
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner2Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Banner Collection #2 (Slideshow)',
            },
        ),
        migrations.CreateModel(
            name='Feature_Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Shop By Brands',
            },
        ),
        migrations.CreateModel(
            name='Featured_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Featured Products',
            },
        ),
        migrations.CreateModel(
            name='SubCategory3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubCategories.subcategory')),
            ],
            options={
                'verbose_name': 'SubCategory #3',
            },
        ),
        migrations.CreateModel(
            name='SubCategory2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubCategories.subcategory')),
            ],
            options={
                'verbose_name': 'SubCategory #2',
            },
        ),
        migrations.CreateModel(
            name='SubCategory1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubCategories.subcategory')),
            ],
            options={
                'verbose_name': 'SubCategory #1',
            },
        ),
        migrations.CreateModel(
            name='Showcase_Products4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.product')),
                ('subcategory3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.subcategory3')),
            ],
            options={
                'verbose_name': 'Feature Products',
            },
        ),
        migrations.CreateModel(
            name='Showcase_Products3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.product')),
                ('subcategory2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.subcategory2')),
            ],
            options={
                'verbose_name': 'Feature Products',
            },
        ),
        migrations.CreateModel(
            name='Showcase_Products2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.product')),
                ('subcategory1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.subcategory1')),
            ],
            options={
                'verbose_name': 'Feature Products',
            },
        ),
        migrations.CreateModel(
            name='Showcase_Products1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.featured_products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.product')),
            ],
            options={
                'verbose_name': 'Feature Products',
            },
        ),
        migrations.CreateModel(
            name='Showcase_brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Brand.brands')),
                ('feature_brands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.feature_brands')),
            ],
            options={
                'verbose_name': 'Feature Brands',
            },
        ),
        migrations.CreateModel(
            name='BannerImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/Banner_Images')),
                ('link', models.CharField(blank=True, max_length=350, null=True)),
                ('banner2carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.banner2carousel')),
            ],
        ),
    ]
