# Generated by Django 3.1.6 on 2021-04-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='link',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
