# Generated by Django 3.1.6 on 2021-04-21 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0002_bannerimage_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('priority',)},
        ),
    ]
