# Generated by Django 3.1.6 on 2021-05-01 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0004_auto_20210423_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerimage',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('priority',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
