# Generated by Django 3.1.6 on 2021-04-02 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon_code',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 16, 7, 50, 485338), verbose_name='Created On'),
        ),
    ]
