# Generated by Django 3.1.6 on 2021-04-02 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commerce', '0003_auto_20210402_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon_code',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 16, 29, 35, 438699), verbose_name='Created On'),
        ),
    ]
