# Generated by Django 3.1.6 on 2021-04-04 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commerce', '0005_auto_20210403_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon_code',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 4, 22, 35, 4, 243054), verbose_name='Created On'),
        ),
    ]
