# Generated by Django 3.1.6 on 2021-04-04 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commerce', '0006_auto_20210404_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon_code',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 4, 23, 0, 29, 442201), verbose_name='Created On'),
        ),
    ]
