# Generated by Django 3.1.6 on 2021-04-05 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commerce', '0007_auto_20210404_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon_code',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 5, 17, 31, 33, 119039), verbose_name='Created On'),
        ),
    ]
