# Generated by Django 3.1.6 on 2021-04-05 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commerce', '0009_auto_20210405_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon_code',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 5, 22, 22, 28, 472489), verbose_name='Created On'),
        ),
    ]
