# Generated by Django 3.1.6 on 2021-04-07 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commerce', '0010_auto_20210405_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon_code',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 11, 29, 5, 100885), verbose_name='Created On'),
        ),
    ]
