# Generated by Django 3.1.6 on 2021-04-07 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commerce', '0014_auto_20210407_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon_code',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 13, 27, 54, 842590), verbose_name='Created On'),
        ),
    ]
