# Generated by Django 3.1.6 on 2021-04-08 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commerce', '0018_auto_20210407_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon_code',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 11, 11, 15, 693323), verbose_name='Created On'),
        ),
    ]
