# Generated by Django 3.1.6 on 2021-04-15 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commerce', '0028_auto_20210414_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon_code',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 22, 28, 53, 413644), verbose_name='Created On'),
        ),
    ]
