# Generated by Django 3.1.6 on 2021-04-21 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commerce', '0030_auto_20210415_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(default='no reason', verbose_name='Cancel Reason (Only to be filled when order is cancelled)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon_code',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 17, 42, 2, 191887), verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Processing', 'Processing'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled')], default='Paid', max_length=50),
        ),
    ]
