# Generated by Django 3.1.6 on 2021-04-23 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commerce', '0033_auto_20210422_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon_code',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 22, 6, 48, 600671), verbose_name='Created On'),
        ),
    ]
