# Generated by Django 3.1.6 on 2021-05-01 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commerce', '0035_auto_20210423_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon_code',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 11, 26, 4, 180399), verbose_name='Created On'),
        ),
    ]
