# Generated by Django 3.1.6 on 2021-05-01 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commerce', '0036_auto_20210501_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon_code',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 13, 43, 0, 752862), verbose_name='Created On'),
        ),
    ]
