# Generated by Django 3.1.6 on 2021-05-01 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commerce', '0037_auto_20210501_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon_code',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 16, 59, 40, 195073), verbose_name='Created On'),
        ),
    ]
