# Generated by Django 3.1.6 on 2021-05-07 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commerce', '0041_auto_20210503_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coupon_code',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 7, 10, 53, 17, 334841), verbose_name='Created On'),
        ),
    ]
