# Generated by Django 3.1.6 on 2021-05-12 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commerce', '0042_auto_20210507_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon_code',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 21, 32, 11, 788690), verbose_name='Created On'),
        ),
    ]
