# Generated by Django 3.1.6 on 2021-04-02 10:19

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SubCategories', '__first__'),
        ('Brand', '0001_initial'),
        ('Categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=400)),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('specifications', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('overview', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('shipping_and_returns', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('published_date', models.DateField(default=datetime.date.today)),
                ('availability', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=200)),
                ('sale', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=50)),
                ('new', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=50)),
                ('previous_price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('current_price', models.PositiveBigIntegerField()),
                ('discount_percentage', models.FloatField(blank=True, null=True)),
                ('thumbnail', models.ImageField(upload_to='images/product images')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Brand.brands')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Categories.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SubCategories.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/product_images')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Shop.product')),
            ],
        ),
    ]
