# Generated by Django 3.1.6 on 2021-04-02 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='Brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='Subcategory',
        ),
    ]
