# Generated by Django 3.1.6 on 2021-04-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20210402_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Subcategory',
            new_name='subcategory',
        ),
    ]
