# Generated by Django 3.1.6 on 2021-04-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_auto_20210405_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Average Rating'),
        ),
    ]
