# Generated by Django 3.1.6 on 2021-04-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_reviews_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
