# Generated by Django 3.1.6 on 2021-04-07 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_product_model_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='full_name',
            field=models.CharField(default='sagyan', max_length=200, verbose_name='Full name'),
            preserve_default=False,
        ),
    ]
