# Generated by Django 3.1.6 on 2021-04-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_auto_20210407_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
