# Generated by Django 3.1.6 on 2021-04-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_auto_20210407_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.FloatField(),
        ),
    ]
