# Generated by Django 3.1.6 on 2021-05-01 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0017_attribute_values_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ManyToManyField(to='Shop.Attribute_Values')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.product')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.variant')),
            ],
        ),
    ]
