# Generated by Django 3.1.6 on 2021-05-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0018_product_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_variant',
            name='attribute',
        ),
        migrations.AddField(
            model_name='product_variant',
            name='attribute',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
