# Generated by Django 3.1.6 on 2021-05-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0019_auto_20210501_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_variant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product_variant',
            name='variant',
        ),
        migrations.DeleteModel(
            name='Attribute_Values',
        ),
        migrations.DeleteModel(
            name='Product_Variant',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
