# Generated by Django 3.1.6 on 2021-04-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubCategories', '0002_auto_20210421_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='page_title',
            field=models.CharField(default='Shop By SubCategory', max_length=300),
            preserve_default=False,
        ),
    ]
