# Generated by Django 3.1.6 on 2021-05-01 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubCategories', '0003_auto_20210423_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('subcategory_priority',), 'verbose_name': 'SubCategory', 'verbose_name_plural': 'SubCategories'},
        ),
    ]
