# Generated by Django 3.1.6 on 2021-04-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0002_auto_20210421_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='page_title',
            field=models.CharField(default='Matechi', max_length=300),
            preserve_default=False,
        ),
    ]
